# -*- coding: utf-8 -*-
"""session2-operators-if-else-loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJIncqudN2wFNZ1P3_1sdJX76pzw-s-4

# Operators in Python

- Arithmetic Operators
- Relational Operators
- Logical Operators
- Bitwise Operators
- Assignment Operators
- Membership Operators
"""

# Arithmetric Operators
print(5+6)

print(5-6)

print(5*6)

print(5/2)

print(5//2)

print(5%2)

print(5**2)

# Relational Operators
print(4>5)

print(4<5)

print(4>=4)

print(4<=4)

print(4==4)

print(4!=4)

# Logical Operators
print(1 and 0)

print(1 or 0)

print(not 1)

# Bitwise Operators

# bitwise and
print(2 & 3)

# bitwise or
print(2 | 3)

# bitwise xor
print(2 ^ 3)

print(~3)

print(4 >> 2)

print(5 << 2)

# Assignment Operators

# =
# a = 2

a = 2

# a = a % 2
a %= 2

# a++ ++a

print(a)

# Membership Operators

# in/not in

print('D' not in 'Delhi')

print(1 in [2,3,4,5,6])

# Program - Find the sum of a 3 digit number entered by the user

number = int(input('Enter a 3 digit number'))

# 345%10 -> 5
a = number%10

number = number//10

# 34%10 -> 4
b = number % 10

number = number//10
# 3 % 10 -> 3
c = number % 10

print(a + b + c)

"""# If-else in Python"""

# login program and indentation
# email -> nitish.campusx@gmail.com
# password -> 1234

email = input('enter email')
password = input('enter password')

if email == 'nitish.campusx@gmail.com' and password == '1234':
  print('Welcome')
elif email == 'nitish.campusx@gmail.com' and password != '1234':
  # tell the user
  print('Incorrect password')
  password = input('enter password again')
  if password == '1234':
    print('Welcome,finally!')
  else:
    print('beta tumse na ho paayega!')
else:
  print('Not correct')

# if-else examples
# 1. Find the min of 3 given numbers
# 2. Menu Driven Program

# min of 3 number

a = int(input('first num'))
b = int(input('second num'))
c = int(input('third num'))

if a<b and a<c:
  print('smallest is',a)
elif b<c:
  print('smallest is',b)
else:
  print('smallest is',c)

# menu driven calculator
menu = input("""
Hi! how can I help you.
1. Enter 1 for pin change
2. Enter 2 for balance check
3. Enter 3 for withdrawl
4. Enter 4 for exit
""")

if menu == '1':
  print('pin change')
elif menu == '2':
  print('balance')
else:
  print('exit')

"""# Modules in Python

- math
- keywords
- random
- datetime
"""

# math
import math

math.sqrt(196)

# keyword
import keyword
print(keyword.kwlist)

# random
import random
print(random.randint(1,100))

# datetime
import datetime
print(datetime.datetime.now())

help('modules')

"""# Loops in Python

- Need for loops
- While Loop
- For Loop
"""

# While loop example -> program to print the table
# Program -> Sum of all digits of a given number
# Program -> keep accepting numbers from users till he/she enters a 0 and then find the avg

number = int(input('enter the number'))

i = 1

while i<11:
  print(number,'*',i,'=',number * i)
  i += 1

# while loop with else

x = 1

while x < 3:
  print(x)
  x += 1

else:
  print('limit crossed')

# Guessing game

# generate a random integer between 1 and 100
import random
jackpot = random.randint(1,100)

guess = int(input('guess karo'))
counter = 1
while guess != jackpot:
  if guess < jackpot:
    print('galat!guess higher')
  else:
    print('galat!guess lower')

  guess = int(input('guess karo'))
  counter += 1

else:
  print('correct guess')
  print('attempts',counter)

# For loop demo

for i in {1,2,3,4,5}:
  print(i)

# For loop examples

"""### Program - The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year. You have to write a program to find out the population at the end of each of the last 10 years."""

curr_pop = 10000

for i in range(10,0,-1):
  print(i,curr_pop)
  curr_pop = curr_pop - 0.1*curr_pop

"""### Sequence sum

1/1! + 2/2! + 3/3! + ...
"""

# code here

# For loop vs While loops (When to use what?)

"""# Nested Loops"""

# Examples

# Program - Unique combination of 1,2,3,4
# Program - Pattern 1 and 2

"""### Pattern 1


*** <br>
**** <br>
***<br>

"""



"""### Pattern 2

1<br>
121<br>
12321<br>
1234321<br>
"""



"""# Loop Control Statement

- Break
- Continue
- Pass
"""

# Break demo

# Break example (Linear Search) -> Prime number in a given range

# Continue demo

# Continue Example (Ecommerce)

# Pass demo