# -*- coding: utf-8 -*-
"""session3-strings-lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1TCiGQM_fyRLX-kM2HZhKdrNY7aZHKA

### Program - The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year. You have to write a program to find out the population at the end of each of the last 10 years.
"""

# Code here
curr_pop = 10000

for i in range(10,0,-1):
  print(i,curr_pop)
  curr_pop = curr_pop/1.1

"""### Sequence sum

1/1! + 2/2! + 3/3! + ...
"""

# Code here

n = int(input('enter n'))

result = 0
fact = 1

for i in range(1,n+1):
  fact = fact * i
  result = result + i/fact

print(result)

"""# Nested Loops"""

# Examples -> unique pairs

for i in range(1,5):
  for j in range(1,5):
    print(i,j)

"""### Pattern 1


*** <br>
**** <br>
***<br>

"""

# code here

rows = int(input('enter number of rows'))

for i in range(1,rows+1):
  for j in range(1,i+1):
    print('*',end='')
  print()

"""### Pattern 2

1<br>
121<br>
12321<br>
1234321<br>
"""

# Code here
rows = int(input('enter number of rows'))

for i in range(1,rows+1):
  for j in range(1,i+1):
    print(j,end='')
  for k in range(i-1,0,-1):
    print(k,end='')

  print()

"""# Loop Control Statement

- Break
- Continue
- Pass
"""

for i in range(1,10):
  if i == 5:
    break
  print(i)

lower = int(input('enter lower range'))
upper = int(input('enter upper range'))

for i in range(lower,upper+1):
  for j in range(2,i):
    if i%j == 0:
      break
  else:
    print(i)

# Continue
for i in range(1,10):
  if i == 5:
    continue
  print(i)

for i in range(1,10):
  pass

"""Strings are sequence of Characters

In Python specifically, strings are a sequence of Unicode Characters

- Creating Strings
- Accessing Strings
- Adding Chars to Strings
- Editing Strings
- Deleting Strings
- Operations on Strings
- String Functions

## Creating Stings
"""

s = 'hello'
s = "hello"
# multiline strings
s = '''hello'''
s = """hello"""
s = str('hello')
print(s)

"it's raining outside"

"""## Accessing Substrings from a String"""

# Positive Indexing
s = 'hello world'
print(s[41])

# Negative Indexing
s = 'hello world'
print(s[-3])

# Slicing
s = 'hello world'
print(s[6:0:-2])

print(s[::-1])

s = 'hello world'
print(s[-1:-6:-1])

"""## Editing and Deleting in Strings"""

s = 'hello world'
s[0] = 'H'

# Python strings are immutable

s = 'hello world'
del s
print(s)

s = 'hello world'
del s[-1:-5:2]
print(s)

"""## Operations on Strings

- Arithmetic Operations
- Relational Operations
- Logical Operations
- Loops on Strings
- Membership Operations
"""

print('delhi' + ' ' + 'mumbai')

print('delhi'*5)

print("*"*50)

'delhi' != 'delhi'

'mumbai' > 'pune'
# lexiographically

'Pune' > 'pune'

'hello' and 'world'

'hello' or 'world'

'' and 'world'

'' or 'world'

'hello' or 'world'

'hello' and 'world'

not 'hello'

for i in 'hello':
  print(i)

for i in 'delhi':
  print('pune')

'D' in 'delhi'







"""## Common Functions
- len
- max
- min
- sorted
"""

len('hello world')

max('hello world')

min('hello world')

sorted('hello world',reverse=True)



"""## Capitalize/Title/Upper/Lower/Swapcase"""

s = 'hello world'
print(s.capitalize())
print(s)

s.title()

s.upper()

'Hello Wolrd'.lower()

'HeLlO WorLD'.swapcase()

"""## Count/Find/Index"""

'my name is nitish'.count('i')

'my name is nitish'.find('x')

'my name is nitish'.index('x')



"""## endswith/startswith"""

'my name is nitish'.endswith('sho')

'my name is nitish'.startswith('1my')

"""## format"""

name = 'nitish'
gender = 'male'

'Hi my name is {1} and I am a {0}'.format(gender,name)

"""## isalnum/ isalpha/ isdigit/ isidentifier"""

'nitish1234%'.isalnum()

'nitish'.isalpha()

'123abc'.isdigit()

'first-name'.isidentifier()



"""## Split/Join"""

'hi my name is nitish'.split()

" ".join(['hi', 'my', 'name', 'is', 'nitish'])

"""## Replace"""

'hi my name is nitish'.replace('nitisrgewrhgh','campusx')

"""## Strip"""

'nitish                           '.strip()

"""## Example Programs"""

# Find the length of a given string without using the len() function

s = input('enter the string')

counter = 0

for i in s:
  counter += 1

print('length of string is',counter)

# Extract username from a given email.
# Eg if the email is nitish24singh@gmail.com
# then the username should be nitish24singh

s = input('enter the email')

pos = s.index('@')
print(s[0:pos])

# Count the frequency of a particular character in a provided string.
# Eg 'hello how are you' is the string, the frequency of h in this string is 2.

s = input('enter the email')
term = input('what would like to search for')

counter = 0
for i in s:
  if i == term:
    counter += 1

print('frequency',counter)

# Write a program which can remove a particular character from a string.
s = input('enter the string')
term = input('what would like to remove')

result = ''

for i in s:
  if i != term:
    result = result + i

print(result)

# Write a program that can check whether a given string is palindrome or not.
# abba
# malayalam

s = input('enter the string')
flag = True
for i in range(0,len(s)//2):
  if s[i] != s[len(s) - i -1]:
    flag = False
    print('Not a Palindrome')
    break

if flag:
  print('Palindrome')

# Write a program to count the number of words in a string without split()

s = input('enter the string')
L = []
temp = ''
for i in s:

  if i != ' ':
    temp = temp + i
  else:
    L.append(temp)
    temp = ''

L.append(temp)
print(L)

# Write a python program to convert a string to title case without using the title()
s = input('enter the string')

L = []
for i in s.split():
  L.append(i[0].upper() + i[1:].lower())

print(" ".join(L))

# Write a program that can convert an integer to string.

number = int(input('enter the number'))

digits = '0123456789'
result = ''
while number != 0:
  result = digits[number % 10] + result
  number = number//10

print(result)
print(type(result))

